package com.softropic.skillars.platform.admin.contract;

public enum AdminActionType {
    MESSAGE_APPROVE, MESSAGE_BLOCK, CONVERSATION_UNBLOCK,
    REVIEW_APPROVE, REVIEW_BLOCK,
    COACH_SUSPEND, COACH_REINSTATE,
    COACH_STRIKE_ISSUED, COACH_STRIKE_DELETED,
    DISPUTE_RESOLVE
}
