app:
  ses:
    from-address: noreply@skillars.com
    enabled: true
  frontend-url: "${APP_FRONTEND_URL:https://skillars.com}"

email:
  retry:
    enabled: true
loki:
  url: ${LOKI_URL:http://localhost:3100}
  enabled: true