#!/usr/bin/env bash
# Generated by docs/deployment/local/setup.sh — the single command that starts the
# local Skillars stack. Re-run setup.sh any time to verify or repair what this needs.
set -euo pipefail
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../.."
docker compose -f docker-compose.yml -f docker-compose.local.yml --env-file .env.local \
  up -d app postgres redis storage-init grafana
cat <<'MSG'

Skillars is starting in the background. First boot can take up to ~60s while
SeaweedFS's healthcheck passes, then Flyway migrations run.

  App:      http://localhost:9990
  Health:   http://localhost:8367/manage/health
  Grafana:  http://localhost:3000

Check status:   docker compose -f docker-compose.yml -f docker-compose.local.yml ps
Tail app logs:  docker compose -f docker-compose.yml -f docker-compose.local.yml logs -f app
Stop:           docker compose -f docker-compose.yml -f docker-compose.local.yml down
MSG
