-- skillars-deferred-92 AC10: give main.platform_config.id an identity, so seed migrations stop
-- hand-picking the next free primary key.
--
-- V20 created the table with `id BIGINT NOT NULL, PRIMARY KEY (id)` and no sequence, so every
-- migration that seeds a config row has had to guess the next free id by reading the ones before it.
-- V99's own header spends six lines on why that is dangerous, and the mechanism is worth restating
-- because it is not the obvious one: the seeds use `ON CONFLICT (key)`, which targets the UNIQUE
-- constraint on `key` — a DIFFERENT constraint from the primary key. So an id collision raises a
-- PRIMARY KEY violation that the ON CONFLICT clause never sees, and Flyway fails on every database
-- that has already run a later migration using that id. The ledger records five separate brushes
-- with this (V25 112-114, V33 id=39, V46 70-72, V48, V53 117-132).
--
-- BY DEFAULT, not ALWAYS. This is the load-bearing choice in the migration.
--   * GENERATED ALWAYS rejects any INSERT that supplies an explicit id. Every historical seed
--     (V20, V25, V33, V46, V48, V53, V93, V99 ...) does exactly that, and Flyway replays all of them
--     from scratch on a fresh database. ALWAYS would therefore break CI and every new environment
--     while continuing to look fine on already-migrated ones — the worst possible failure shape.
--   * GENERATED BY DEFAULT leaves the historical inserts working and supplies a value only when one
--     is omitted, which is what new seeds will do.
--
-- The sequence is seeded from the live maximum, computed here rather than hardcoded: hardcoding it
-- would reintroduce the same "guess the next free number" problem this migration exists to remove.
-- COALESCE covers the empty-table case, and it is is_called — not the value — that has to carry it.
-- setval(seq, v, true) makes the NEXT nextval() return v + 1; setval(seq, v, false) returns v itself.
-- So a populated table wants (max(id), true) and an empty one wants (1, false). Lowering the value
-- to COALESCE(max(id), 0) instead does NOT work and is not merely suboptimal: the identity sequence
-- has the default MINVALUE 1, so setval(seq, 0, true) raises
--   ERROR: setval: value 0 is out of bounds for sequence "platform_config_id_seq" (1..92233...)
-- and the migration aborts. Verified against postgres:17-alpine, which is the image this project
-- runs (code review of the code review, skillars-deferred-92).
--
-- MigrationLint.Rule.PLATFORM_CONFIG_EXPLICIT_ID now fails the build on any future
-- `INSERT INTO main.platform_config (id, ...)`, so the old pattern cannot come back.

-- ACCESS EXCLUSIVE on main.platform_config for the duration of the ALTER. The table is a small
-- configuration table (~130 rows) and the operation is catalog-only, so the statement itself is
-- instantaneous — but a bounded wait is still required (skillars-deferred-92 AC8): without it, an
-- ALTER blocked behind a long-running reader makes every subsequent query on the table queue behind
-- the ALTER, and ConfigService reads this table on a 5-minute refresh from every node.
SET lock_timeout = '5s';

ALTER TABLE main.platform_config
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Start above every id the historical seeds have already claimed. pg_get_serial_sequence resolves
-- the sequence the identity just created, so the name is never hardcoded either.
SELECT setval(
    pg_get_serial_sequence('main.platform_config', 'id'),
    (SELECT COALESCE(max(id), 1) FROM main.platform_config),
    (SELECT count(*) > 0 FROM main.platform_config)
);
