-- skillars-deferred-106 AC13.2: seed the completion-gated payout config.
-- (Story text calls this V131; renumbered to V134 — V130-V132 were taken by other merged stories.)
--
-- payment.payout.hold_hours (D5): the delay between BookingCompletedEvent and the coach transfer.
-- Default 48. The COACH_PAYOUT_TRANSFER outbox handler defers the transfer until
-- completed_at + hold_hours (coach_payouts.release_after). A dispute raised inside the hold window
-- cancels the still-pending payout outright (no pay-then-reverse); a dispute after release takes the
-- Transfer.createReversal path. Bounded 0-336h (14d = disputes.submissionWindowDays, the longest
-- sane hold) by ConfigService.getBoundedLong. Setting it to 0 restores release-on-completion with
-- no code change.
--
-- id is OMITTED — main.platform_config.id is GENERATED BY DEFAULT AS IDENTITY since V128, and
-- MigrationLint.Rule.PLATFORM_CONFIG_EXPLICIT_ID fails the build on a hand-picked id.
-- Config seeds take no lock — no lock_timeout directive needed.
INSERT INTO main.platform_config (key, value, value_type, description, updated_at)
VALUES ('payment.payout.hold_hours', '48', 'LONG',
        'Hours to hold a completed session''s coach payout before the Stripe transfer fires '
        || '(skillars-deferred-106). Bounded 0-336 (14d dispute window). 0 = release on completion. '
        || 'A dispute inside the hold cancels the pending COACH_PAYOUT_TRANSFER outbox row; a dispute '
        || 'after release triggers a Transfer reversal.', NOW())
ON CONFLICT (key) DO NOTHING;
