-- ============================================================
-- V139: Pre-production seed data baseline (skillars-deferred-112)
--
-- Companion to V138 (which is pure DDL, zero DML). Reproduces the FINAL
-- state of every table any pre-squash migration seeded, generated with
-- `pg_dump --data-only --no-owner --column-inserts --on-conflict-do-nothing`
-- against the same reference database as V138 (V02..V137, pre-squash commit
-- 4a3f218dabd04e0c8419282e922f60de5f93934d) -- not by concatenating the
-- historical INSERT statements. See docs/deployment/migration-rebaseline.md
-- for the full per-table rationale; summary:
--
--   main.authority          5 rows  -- ROLE_COACH/PARENT/PLAYER/ADMIN/LTD_ADMIN.
--                                      ids 100-104 preserved verbatim: they are
--                                      FK targets of user_authority.authority_id.
--   main.platform_config  120 rows  -- id column dropped (V128 made it an
--                                      identity column; MigrationLint's
--                                      PLATFORM_CONFIG_EXPLICIT_ID rule exists
--                                      for exactly this reason, and it's correct
--                                      on the merits even though V139 itself
--                                      sits at the grandfather baseline and
--                                      isn't linted). updated_at column dropped
--                                      (defaults to now()); a literal dump-time
--                                      timestamp has no business meaning here.
--   session.drills          20 rows -- ids preserved verbatim: V39 originally
--                                      seeded these with gen_random_uuid(), and
--                                      V111 exists solely to replace those
--                                      random ids with the deterministic ones
--                                      below (matched by trans_key). Copying
--                                      V39's inserts instead would silently
--                                      reintroduce the exact bug V111 fixed.
--                                      created_at/updated_at columns dropped
--                                      (both default to now()) for the same
--                                      reason as platform_config.updated_at.
--   development.skill_definitions
--                          15 rows  -- the radar skill catalog (PAC/SHO/PAS/...).
--
-- Every statement is `ON CONFLICT (<natural key>) DO NOTHING`, so re-running
-- this file against an already-seeded database inserts zero rows and raises
-- no error. The platform_config identity sequence is bumped past every id
-- that any pre-squash migration ever issued (606, not 121) so a freshly
-- application-generated config row can never collide with a historical id
-- that some external reference might still assume -- defensive, since none
-- is known to exist, but cheap.
--
-- main.authority.created_date uses NOW() rather than the literal dump-time
-- timestamp pg_dump captured, for the same reason updated_at/created_at are
-- dropped elsewhere: a frozen historical instant has no business meaning in
-- a baseline meant to be re-run fresh at any future date.
-- ============================================================

INSERT INTO main.authority (id, name, status, created_by, created_date) VALUES (100, 'ROLE_COACH', 'ACTIVE', 'system', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO main.authority (id, name, status, created_by, created_date) VALUES (101, 'ROLE_PARENT', 'ACTIVE', 'system', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO main.authority (id, name, status, created_by, created_date) VALUES (102, 'ROLE_PLAYER', 'ACTIVE', 'system', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO main.authority (id, name, status, created_by, created_date) VALUES (103, 'ROLE_ADMIN', 'ACTIVE', 'system', NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO main.authority (id, name, status, created_by, created_date) VALUES (104, 'ROLE_LTD_ADMIN', 'ACTIVE', 'system', NOW()) ON CONFLICT (id) DO NOTHING;

INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('booking.batch.maxSize', '5', 'LONG', 'Maximum number of slots a parent can request in a single bulk batch') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('booking.payment_pending_sweep_grace_minutes', '120', 'LONG', 'Minutes a booking may sit in PAYMENT_PENDING before PaymentPendingSweeper treats it as stranded') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('booking.quick_complete_timeout_hours', '24', 'LONG', 'Hours before un-confirmed Quick Complete auto-confirms') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('booking.request_expiry_hours', '48', 'LONG', 'Hours before unaccepted booking request auto-expires') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('booking.session.defaultDurationMinutes', '60', 'LONG', 'Default coaching session length in minutes; a coach may override it on their pricing row. ConfigService caches with a 5-minute TTL, so a change here applies within 5 minutes, not instantly.') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('coach.tier.academy.bandwidth_quota_gb', '200', 'LONG', 'Academy bandwidth quota GB/month') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('coach.tier.academy.drill_library', 'true', 'STRING', 'Academy: drill library access') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('coach.tier.academy.session_builder', 'true', 'STRING', 'Academy: session builder access') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('coach.tier.academy.storage_quota_gb', '50', 'LONG', 'Academy storage quota in GB') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('coach.tier.academy.video_upload', 'true', 'STRING', 'Academy: video upload capability') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('coach.tier.instructor.bandwidth_quota_gb', '80', 'LONG', 'Instructor bandwidth quota GB/month') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('coach.tier.instructor.drill_library', 'true', 'STRING', 'Instructor: drill library access') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('coach.tier.instructor.session_builder', 'true', 'STRING', 'Instructor: session builder access') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('coach.tier.instructor.storage_quota_gb', '20', 'LONG', 'Instructor storage quota in GB') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('coach.tier.instructor.video_upload', 'true', 'STRING', 'Instructor: video upload capability') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('coach.tier.scout.bandwidth_quota_gb', '20', 'LONG', 'Scout bandwidth quota GB/month') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('coach.tier.scout.drill_library', 'true', 'STRING', 'Scout: drill library access') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('coach.tier.scout.session_builder', 'true', 'STRING', 'Scout: session builder access') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('coach.tier.scout.storage_quota_gb', '5', 'LONG', 'Scout storage quota in GB') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('coach.tier.scout.video_upload', 'false', 'STRING', 'Scout: video upload capability') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('development.correlation.minSessionCount', '5', 'LONG', 'Minimum distinct completed sessions required before the Development Correlation Engine shows insights') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('development.neglectedSkill.warmupSessionCount', '5', 'LONG', 'Minimum distinct completed sessions a player must have logged before NeglectedSkillProcessor evaluates them — avoids flagging every coach-targeted skill on a brand-new player''s first evaluation') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('development.timeline.coachAccessExpiryDays', '90', 'LONG', 'Days of inactivity after which a coach loses access to a player timeline') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('disputes.submissionWindowDays', '14', 'LONG', 'Days after booking completion/cancellation within which a dispute can be raised') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('feature.drillVideoUpload.enabled.ACADEMY', 'true', 'STRING', 'Drill video upload gate: Academy tier') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('feature.drillVideoUpload.enabled.INSTRUCTOR', 'true', 'STRING', 'Drill video upload gate: Instructor tier') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('feature.drillVideoUpload.enabled.SCOUT', 'false', 'STRING', 'Drill video upload gate: Scout tier') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('feature.sessionBuilder.enabled.ACADEMY', 'true', 'STRING', 'Session Builder gate: Academy tier') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('feature.sessionBuilder.enabled.INSTRUCTOR', 'true', 'STRING', 'Session Builder gate: Instructor tier') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('feature.sessionBuilder.enabled.SCOUT', 'false', 'STRING', 'Session Builder gate: Scout tier') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('gdpr.export.urlExpiryHours', '48', 'LONG', 'Hours before a GDPR export download URL expires') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('pack.expiry.days.tier1', '90', 'LONG', '1-session pack validity in days') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('pack.expiry.days.tier2', '180', 'LONG', '2-5 session pack validity in days') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('pack.expiry.days.tier3', '365', 'LONG', '6-10 session pack validity in days') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('pack.expiry.days.tier4', '548', 'LONG', '11+ session pack validity in days') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('pack.pause.maxDays', '90', 'LONG', 'Maximum days a pack can be paused') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('payment.payout.hold_hours', '48', 'LONG', 'Hours to hold a completed session''s coach payout before the Stripe transfer fires (skillars-deferred-106). Bounded 0-336 (14d dispute window). 0 = release on completion. A dispute inside the hold cancels the pending COACH_PAYOUT_TRANSFER outbox row; a dispute after release triggers a Transfer reversal.') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('payment.stripe.feeFixed', '0.25', 'STRING', 'Stripe fixed fee per credit cash-out transaction (EUR). Default €0.25.') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('payment.stripe.feeRate', '0.025', 'STRING', 'Stripe processing fee rate for credit cash-outs. Default 2.5% (0.025).') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.admin_alert_email', '', 'STRING', 'Admin alert recipient email for moderation events (CSAM, service unavailability)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.commission.rate', '0.08', 'STRING', 'Platform commission rate deducted from each session payment via Stripe application_fee_amount. Default 8% (0.08).') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.commission_rate', '0.08', 'STRING', 'Platform commission rate (decimal)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.message_retention_months', '24', 'LONG', 'Message retention period in months') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.messaging.moderation_orphan_grace_minutes', '30', 'LONG', 'Minutes a message may sit in PENDING moderation before MessageModerationSweeper treats it as stranded') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.moderation_lock_timeout_minutes', '15', 'LONG', 'Moderation in-flight lock duration in minutes — SLA monitor skips videos with active lock') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.moderation_max_retries', '5', 'LONG', 'Max SLA monitor retries before video is permanently failed') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.moderation_sla_minutes', '30', 'LONG', 'Moderation SLA window in minutes — videos stuck in SCANNING beyond this are re-queued') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.payment.currency', 'eur', 'STRING', 'ISO 4217 currency code (lowercase, as Stripe''s API expects) used for all Stripe charges. Single-currency platform today; extracted from a hardcoded literal so a future multi-currency change does not require a code deploy for this value alone.') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.reliability_strike_expiry_days', '90', 'LONG', 'Days before reliability strike expires') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.reminder_interval_primary_hours', '24', 'LONG', 'Primary reminder interval before session (hours)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.reminder_interval_secondary_hours', '2', 'LONG', 'Secondary reminder interval before session (hours)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.strike_threshold.admin_alert', '3', 'LONG', 'Strikes before admin alert is triggered') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.strike_threshold.auto_suspension', '5', 'LONG', 'Strikes before automatic suspension') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.timeline_access_expiry_days', '30', 'LONG', 'Days of timeline access after relationship ends') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.video.access.coach_window_days', '90', 'LONG', 'Days within which a coach with a completed booking can access a player video') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.video.approval.auto_reject_days', '7', 'STRING', 'Days until a PENDING approval would auto-reject. WARNING: not yet active — no scheduler wired. See Story backlog.') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.video.approval.notification_enabled', 'true', 'STRING', 'Controls whether VideoApprovalParentNotificationEvent is published when a minor-gate approval is created') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.video.approvalCancellation.enabled', 'true', 'STRING', 'Enable approval-request cancellation on video deletion (Story 6.6 deploys before or alongside Story 6.5)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.video.deletion.max_attempts', '5', 'LONG', 'Max Bunny.net deletion attempts before outbox row transitions to DEAD') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.video.deletion.outbox_poll_delay_ms', '60000', 'LONG', 'Outbox processor poll interval in milliseconds') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.video.lifecycle.archived_to_deleted_days', '90', 'LONG', 'Days an ARCHIVED video waits before physical deletion') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.video.lifecycle.batch_size', '100', 'LONG', 'Lifecycle scheduler batch size per phase run') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.video.lifecycle.blocked_to_archived_days', '30', 'LONG', 'Days a BLOCKED video waits before transitioning to ARCHIVED') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.video.lifecycle.outbox_max_attempts', '5', 'LONG', 'Max retry attempts for subscription lifecycle outbox before dead-letter') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.video.playback.ip_binding_enabled', 'false', 'STRING', 'Bind signed playback URLs to the requestor client IP') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.video.playback.signed_url_ttl_minutes', '120', 'LONG', 'Signed HLS URL TTL in minutes (default 2 hours)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.video_reservation_timeout_minutes', '60', 'LONG', 'Video upload reservation timeout in minutes') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('platform.video_signed_url_ttl_seconds', '7200', 'LONG', 'Video signed URL TTL in seconds (2 hours)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('player.tier.athlete.bandwidth_quota_gb', '10', 'LONG', 'Athlete bandwidth quota GB/month') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('player.tier.athlete.skills_radar', 'false', 'STRING', 'Athlete: skills radar access') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('player.tier.athlete.storage_quota_gb', '2', 'LONG', 'Athlete storage quota in GB') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('player.tier.athlete.video_access', 'false', 'STRING', 'Athlete: video access') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('player.tier.pro.bandwidth_quota_gb', '40', 'LONG', 'Pro bandwidth quota GB/month') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('player.tier.pro.skills_radar', 'true', 'STRING', 'Pro: skills radar access') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('player.tier.pro.storage_quota_gb', '10', 'LONG', 'Pro storage quota in GB') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('player.tier.pro.video_access', 'true', 'STRING', 'Pro: video access') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('player.tier.semi_pro.bandwidth_quota_gb', '20', 'LONG', 'Semi-Pro bandwidth quota GB/month') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('player.tier.semi_pro.skills_radar', 'true', 'STRING', 'Semi-Pro: skills radar access') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('player.tier.semi_pro.storage_quota_gb', '5', 'LONG', 'Semi-Pro storage quota in GB') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('player.tier.semi_pro.video_access', 'true', 'STRING', 'Semi-Pro: video access') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('reliability.strike.suspensionThreshold', '5', 'STRING', 'Rolling 30-day strike count triggering PENDING_REVIEW. Default 5.') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('reliability.strike.visibilityThreshold', '3', 'STRING', 'Rolling 30-day strike count at which coach visibility is reduced. Default 3.') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('reviews.autoHoldFlagThreshold', '3', 'LONG', 'Number of open flags required to auto-hold a review for admin moderation') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('reviews.submissionWindowDays', '14', 'LONG', 'Days within which a completed session must exist to submit/update a review') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('security.age-policy.teen-max-age', '17', 'LONG', 'Maximum age (inclusive) for 13-17 tier') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('security.age-policy.u10-max-age', '9', 'LONG', 'Maximum age (inclusive) for U10 tier') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('security.age-policy.young-teen-max-age', '12', 'LONG', 'Maximum age (inclusive) for 10-12 tier') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('security.login.lock-window-minutes', '15', 'LONG', 'Lock window in minutes for failed logins') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('security.login.max-attempts', '5', 'LONG', 'Max failed login attempts before lockout') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('security.registration.phone-otp-required', 'false', 'STRING', 'Whether phone OTP verification is required before a Player/Parent/Coach account can log in') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('slu.intensity.scale', '0.10', 'STRING', 'SLU intensity modifier scale (intensity × scale = multiplier)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('slu.matchRealism.scale', '0.10', 'STRING', 'SLU match realism modifier scale (matchRealism × scale = multiplier)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('slu.neglected.threshold', '0.30', 'STRING', 'Neglected skill threshold: flag if actual < target × (1 - threshold)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('slu.pressure.scale', '0.10', 'STRING', 'SLU pressure modifier scale (pressureLevel × scale = multiplier)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('subscription.coach.academy.monthly.priceId', '', 'STRING', 'Stripe priceId: Academy monthly billing (set in admin before launch)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('subscription.coach.instructor.monthly.priceId', '', 'STRING', 'Stripe priceId: Instructor monthly billing (set in admin before launch)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('subscription.pastDue.gracePeriodDays', '7', 'LONG', 'Days before PAST_DUE triggers automatic tier downgrade') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('subscription.player.athlete.monthly.priceId', '', 'STRING', 'Stripe priceId: Athlete monthly billing') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('subscription.player.athlete.quarterly.priceId', '', 'STRING', 'Stripe priceId: Athlete quarterly billing') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('subscription.player.athlete.yearly.priceId', '', 'STRING', 'Stripe priceId: Athlete yearly billing') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('subscription.player.pro.yearly.priceId', '', 'STRING', 'Stripe priceId: Pro yearly billing (YEARLY only per FR-PAY-007)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('subscription.player.semi_pro.yearly.priceId', '', 'STRING', 'Stripe priceId: Semi-Pro yearly billing (YEARLY only per FR-PAY-007)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('video.coachReview.maxDurationSeconds', '300', 'STRING', 'Coach review: max duration (300s)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('video.coachReview.maxSizeBytes', '1073741824', 'STRING', 'Coach review: max size (1 GiB)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('video.drillDemo.maxDurationSeconds', '120', 'STRING', 'Drill demo max duration (seconds)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('video.drillDemo.maxSizeBytes', '524288000', 'STRING', 'Drill demo max size (500 MB in bytes)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('video.homework.maxDurationSeconds', '60', 'STRING', 'Homework: max duration (60s)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('video.homework.maxSizeBytes', '262144000', 'STRING', 'Homework: max size (250 MiB)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('video.quota.academy.bandwidthBytesMonthly', '214748364800', 'STRING', 'Academy: monthly bandwidth (200 GiB)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('video.quota.academy.storageBytes', '21474836480', 'STRING', 'Academy: video storage quota (20 GiB)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('video.quota.athlete.bandwidthBytesMonthly', '10737418240', 'STRING', 'Athlete: monthly bandwidth (10 GiB)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('video.quota.athlete.storageBytes', '2147483648', 'STRING', 'Athlete: video storage quota (2 GiB)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('video.quota.instructor.bandwidthBytesMonthly', '53687091200', 'STRING', 'Instructor: monthly bandwidth (50 GiB)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('video.quota.instructor.storageBytes', '5368709120', 'STRING', 'Instructor: video storage quota (5 GiB)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('video.quota.pro.bandwidthBytesMonthly', '53687091200', 'STRING', 'Pro: monthly bandwidth (50 GiB)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('video.quota.pro.storageBytes', '7516192768', 'STRING', 'Pro: video storage quota (7 GiB)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('video.quota.scout.bandwidthBytesMonthly', '5368709120', 'STRING', 'Scout: monthly bandwidth (5 GiB)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('video.quota.scout.storageBytes', '0', 'STRING', 'Scout: video storage quota (0 = no upload)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('video.quota.semiPro.bandwidthBytesMonthly', '26843545600', 'STRING', 'Semi-Pro: monthly bandwidth (25 GiB)') ON CONFLICT (key) DO NOTHING;
INSERT INTO main.platform_config (key, value, value_type, description) VALUES ('video.quota.semiPro.storageBytes', '4294967296', 'STRING', 'Semi-Pro: video storage quota (4 GiB)') ON CONFLICT (key) DO NOTHING;

INSERT INTO session.drills (id, name, description, library_type, owner_coach_id, status, metadata, trans_key, version, source_drill_id) VALUES ('00000000-0000-4000-8000-000000000001', 'Toe Taps', 'Rapid alternating toe taps on top of the ball to develop quick feet and ball feel.', 'PLATFORM', NULL, 'ACTIVE', '{"intensity": 2, "repDensity": 40, "matchRealism": 1, "weakFootBias": true, "cognitiveLoad": 1, "pressureLevel": 1, "primarySkills": ["ball_mastery"], "coachingPoints": ["Keep the ball close under your feet", "Use the front pad of each toe", "Increase speed gradually", "Stay light on your feet"], "difficultyTier": "U8", "skillWeighting": {"balance": 10, "ball_mastery": 70, "coordination": 20}, "secondarySkills": ["coordination", "balance"], "equipmentRequired": ["ball"], "recommendedGroupSize": "1–4"}', 'sessDrill.toeTaps', 0, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO session.drills (id, name, description, library_type, owner_coach_id, status, metadata, trans_key, version, source_drill_id) VALUES ('00000000-0000-4000-8000-000000000002', 'Inside-Outside Roll', 'Roll the ball across the body using inside-outside foot alternations to build touch and control.', 'PLATFORM', NULL, 'ACTIVE', '{"intensity": 2, "repDensity": 20, "matchRealism": 2, "weakFootBias": true, "cognitiveLoad": 2, "pressureLevel": 1, "primarySkills": ["ball_mastery", "close_control"], "coachingPoints": ["Soft touch on every contact", "Eyes up between touches", "Stay balanced over the ball", "Progress to both feet equally"], "difficultyTier": "U10", "skillWeighting": {"footwork": 10, "ball_mastery": 60, "close_control": 30}, "secondarySkills": ["footwork"], "equipmentRequired": ["ball"], "recommendedGroupSize": "1–6"}', 'sessDrill.insideOutsideRoll', 0, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO session.drills (id, name, description, library_type, owner_coach_id, status, metadata, trans_key, version, source_drill_id) VALUES ('00000000-0000-4000-8000-000000000003', 'L-Shape Mastery', 'Player uses sole to pull back, then inside foot to drag the ball in an L-pattern.', 'PLATFORM', NULL, 'ACTIVE', '{"intensity": 2, "repDensity": 16, "matchRealism": 2, "weakFootBias": false, "cognitiveLoad": 2, "pressureLevel": 1, "primarySkills": ["ball_mastery", "close_control"], "coachingPoints": ["Plant foot points in direction of travel", "Sole pull stays behind the body line", "Drive away with purpose after the shape", "Build speed only after technique is clean"], "difficultyTier": "U10", "skillWeighting": {"ball_mastery": 55, "close_control": 30, "change_of_direction": 15}, "secondarySkills": ["change_of_direction"], "equipmentRequired": ["ball", "cones"], "recommendedGroupSize": "1–4"}', 'sessDrill.lShapeMastery', 0, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO session.drills (id, name, description, library_type, owner_coach_id, status, metadata, trans_key, version, source_drill_id) VALUES ('00000000-0000-4000-8000-000000000004', 'Foundation Juggling Sequence', 'Structured juggling progression: thigh-to-thigh, foot-to-thigh, continuous foot juggle.', 'PLATFORM', NULL, 'ACTIVE', '{"intensity": 1, "repDensity": 30, "matchRealism": 1, "weakFootBias": true, "cognitiveLoad": 2, "pressureLevel": 1, "primarySkills": ["ball_mastery", "first_touch"], "coachingPoints": ["Cushion the ball on contact — don''t stab", "Minimal knee bend to control height", "Use laces not toes for clean strikes", "Track the ball all the way to contact"], "difficultyTier": "U12", "skillWeighting": {"first_touch": 35, "ball_mastery": 50, "coordination": 15}, "secondarySkills": ["coordination", "aerial_control"], "equipmentRequired": ["ball"], "recommendedGroupSize": "1–8"}', 'sessDrill.foundationJugglingSequence', 0, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO session.drills (id, name, description, library_type, owner_coach_id, status, metadata, trans_key, version, source_drill_id) VALUES ('00000000-0000-4000-8000-000000000005', 'Cone Slalom Ball Mastery', 'Player dribbles a cone slalom using only inside and outside touches.', 'PLATFORM', NULL, 'ACTIVE', '{"intensity": 3, "repDensity": 10, "matchRealism": 3, "weakFootBias": false, "cognitiveLoad": 2, "pressureLevel": 2, "primarySkills": ["close_control", "dribbling"], "coachingPoints": ["Keep the ball within 1 foot of your body", "Lean into each gate", "Use alternate feet at each cone", "Accelerate between gates"], "difficultyTier": "U12", "skillWeighting": {"dribbling": 35, "ball_mastery": 15, "close_control": 50}, "secondarySkills": ["ball_mastery", "agility"], "equipmentRequired": ["ball", "cones"], "recommendedGroupSize": "2–8"}', 'sessDrill.coneSlalomBallMastery', 0, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO session.drills (id, name, description, library_type, owner_coach_id, status, metadata, trans_key, version, source_drill_id) VALUES ('00000000-0000-4000-8000-000000000006', 'Static Finish — Inside Foot', 'Stationary shooting practice using the inside foot for placement and accuracy.', 'PLATFORM', NULL, 'ACTIVE', '{"intensity": 2, "repDensity": 20, "matchRealism": 2, "weakFootBias": true, "cognitiveLoad": 1, "pressureLevel": 1, "primarySkills": ["finishing", "shooting_technique"], "coachingPoints": ["Lock the ankle on contact", "Strike through the middle of the ball", "Non-kicking foot beside the ball", "Follow through toward target"], "difficultyTier": "U8", "skillWeighting": {"accuracy": 10, "finishing": 60, "shooting_technique": 30}, "secondarySkills": ["accuracy"], "equipmentRequired": ["ball", "goal"], "recommendedGroupSize": "2–6"}', 'sessDrill.staticFinishInsideFoot', 0, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO session.drills (id, name, description, library_type, owner_coach_id, status, metadata, trans_key, version, source_drill_id) VALUES ('00000000-0000-4000-8000-000000000007', 'Turn and Shoot', 'Receive a pass with back to goal, turn, and shoot first time.', 'PLATFORM', NULL, 'ACTIVE', '{"intensity": 3, "repDensity": 12, "matchRealism": 4, "weakFootBias": false, "cognitiveLoad": 3, "pressureLevel": 2, "primarySkills": ["finishing", "first_touch"], "coachingPoints": ["Check shoulder before the ball arrives", "Decide turn direction before receiving", "Positive first touch away from goal", "Strike early — don''t over-touch"], "difficultyTier": "U14", "skillWeighting": {"turning": 20, "finishing": 45, "first_touch": 35}, "secondarySkills": ["turning", "decision_making"], "equipmentRequired": ["ball", "goal", "cones"], "recommendedGroupSize": "3–8"}', 'sessDrill.turnAndShoot', 0, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO session.drills (id, name, description, library_type, owner_coach_id, status, metadata, trans_key, version, source_drill_id) VALUES ('00000000-0000-4000-8000-000000000008', 'Shooting on the Move', 'Player receives a lateral pass while moving and finishes on goal without breaking stride.', 'PLATFORM', NULL, 'ACTIVE', '{"intensity": 3, "repDensity": 14, "matchRealism": 4, "weakFootBias": true, "cognitiveLoad": 2, "pressureLevel": 2, "primarySkills": ["shooting_technique", "finishing"], "coachingPoints": ["Keep head steady through contact", "Plant foot pointed at the target", "Strike before pace is lost", "Aim for corners — power without control is wasted"], "difficultyTier": "U14", "skillWeighting": {"movement": 15, "finishing": 35, "shooting_technique": 50}, "secondarySkills": ["movement", "coordination"], "equipmentRequired": ["ball", "goal", "cones"], "recommendedGroupSize": "2–6"}', 'sessDrill.shootingOnTheMove', 0, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO session.drills (id, name, description, library_type, owner_coach_id, status, metadata, trans_key, version, source_drill_id) VALUES ('00000000-0000-4000-8000-000000000009', '1v1 Finishing Under Pressure', 'Attacker receives, beats a passive defender, and shoots within a 5-second window.', 'PLATFORM', NULL, 'ACTIVE', '{"intensity": 4, "repDensity": 10, "matchRealism": 5, "weakFootBias": false, "cognitiveLoad": 4, "pressureLevel": 4, "primarySkills": ["finishing", "dribbling_under_pressure"], "coachingPoints": ["Commit the defender before the move", "Create the angle — don''t shoot from straight on", "Stay calm — your foot technique does not change under pressure", "Score with purpose not panic"], "difficultyTier": "U16", "skillWeighting": {"finishing": 40, "decision_making": 25, "dribbling_under_pressure": 35}, "secondarySkills": ["decision_making", "composure"], "equipmentRequired": ["ball", "goal", "cones"], "recommendedGroupSize": "4–10"}', 'sessDrill.oneVOneFinishingUnderPressure', 0, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO session.drills (id, name, description, library_type, owner_coach_id, status, metadata, trans_key, version, source_drill_id) VALUES ('00000000-0000-4000-8000-000000000010', 'Volley Finishing', 'Players practice volleys from crossed balls or throws, focusing on technique and timing.', 'PLATFORM', NULL, 'ACTIVE', '{"intensity": 3, "repDensity": 10, "matchRealism": 4, "weakFootBias": true, "cognitiveLoad": 3, "pressureLevel": 2, "primarySkills": ["shooting_technique", "aerial_control"], "coachingPoints": ["Watch the ball all the way to contact", "Get side-on — do not face the ball square", "Keep toes down and lock ankle", "Aim across goal for placement"], "difficultyTier": "U16", "skillWeighting": {"timing": 20, "aerial_control": 30, "shooting_technique": 50}, "secondarySkills": ["finishing", "timing"], "equipmentRequired": ["ball", "goal"], "recommendedGroupSize": "3–8"}', 'sessDrill.volleyFinishing', 0, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO session.drills (id, name, description, library_type, owner_coach_id, status, metadata, trans_key, version, source_drill_id) VALUES ('00000000-0000-4000-8000-000000000011', 'Cruyff Turn', 'Classic feint: fake to pass or cross, pull ball behind standing leg with inside foot.', 'PLATFORM', NULL, 'ACTIVE', '{"intensity": 2, "repDensity": 14, "matchRealism": 3, "weakFootBias": false, "cognitiveLoad": 2, "pressureLevel": 2, "primarySkills": ["dribbling", "turning"], "coachingPoints": ["Sell the fake with your body lean", "Drag behind the standing leg — not across", "Explode out in new direction immediately", "Head up after turn to make next decision"], "difficultyTier": "U12", "skillWeighting": {"turning": 35, "deception": 15, "dribbling": 50}, "secondarySkills": ["deception", "close_control"], "equipmentRequired": ["ball", "cones"], "recommendedGroupSize": "2–8"}', 'sessDrill.cruyffTurn', 0, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO session.drills (id, name, description, library_type, owner_coach_id, status, metadata, trans_key, version, source_drill_id) VALUES ('00000000-0000-4000-8000-000000000012', 'Step-Over to Accelerate', 'Use step-over(s) to unbalance a defender, then burst into space with outside foot.', 'PLATFORM', NULL, 'ACTIVE', '{"intensity": 3, "repDensity": 16, "matchRealism": 4, "weakFootBias": true, "cognitiveLoad": 2, "pressureLevel": 2, "primarySkills": ["dribbling", "skill_moves"], "coachingPoints": ["Circle the ball — don''t kick it", "Plant foot stays behind ball line", "Drive outside foot away immediately", "Lean opposite direction to the step-over"], "difficultyTier": "U14", "skillWeighting": {"dribbling": 55, "skill_moves": 30, "acceleration": 15}, "secondarySkills": ["agility", "acceleration"], "equipmentRequired": ["ball", "cones"], "recommendedGroupSize": "2–8"}', 'sessDrill.stepOverToAccelerate', 0, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO session.drills (id, name, description, library_type, owner_coach_id, status, metadata, trans_key, version, source_drill_id) VALUES ('00000000-0000-4000-8000-000000000013', 'Elastico / Flip-Flap', 'Touch ball outside then whip inside with same foot in one fast motion to beat the defender.', 'PLATFORM', NULL, 'ACTIVE', '{"intensity": 3, "repDensity": 12, "matchRealism": 3, "weakFootBias": false, "cognitiveLoad": 3, "pressureLevel": 2, "primarySkills": ["skill_moves", "close_control"], "coachingPoints": ["The outside touch is the fake", "Whip inside must be sharp and low", "Keep ball very close — inches not feet", "Practise slowly first before adding speed"], "difficultyTier": "U16", "skillWeighting": {"deception": 15, "skill_moves": 60, "close_control": 25}, "secondarySkills": ["dribbling", "deception"], "equipmentRequired": ["ball", "cones"], "recommendedGroupSize": "1–6"}', 'sessDrill.elasticoFlipFlap', 0, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO session.drills (id, name, description, library_type, owner_coach_id, status, metadata, trans_key, version, source_drill_id) VALUES ('00000000-0000-4000-8000-000000000014', 'Pressure Escape Rondo (3v1)', 'Three passers keep the ball in a small square from one defender; after 5 passes, player must dribble out.', 'PLATFORM', NULL, 'ACTIVE', '{"intensity": 4, "repDensity": 8, "matchRealism": 5, "weakFootBias": false, "cognitiveLoad": 5, "pressureLevel": 5, "primarySkills": ["dribbling_under_pressure", "close_control"], "coachingPoints": ["Protect the ball with your body", "Take the ball away from pressure — not into it", "Head up: see all three passers", "Disguise your exit before you take it"], "difficultyTier": "U16", "skillWeighting": {"close_control": 30, "decision_making": 30, "dribbling_under_pressure": 40}, "secondarySkills": ["decision_making", "awareness", "passing"], "equipmentRequired": ["ball", "cones"], "recommendedGroupSize": "4"}', 'sessDrill.pressureEscapeRondo3v1', 0, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO session.drills (id, name, description, library_type, owner_coach_id, status, metadata, trans_key, version, source_drill_id) VALUES ('00000000-0000-4000-8000-000000000015', 'Body Feint and Drive', 'Drop shoulder to fake one direction, drive past passive defender with outside foot on opposite side.', 'PLATFORM', NULL, 'ACTIVE', '{"intensity": 3, "repDensity": 14, "matchRealism": 4, "weakFootBias": true, "cognitiveLoad": 3, "pressureLevel": 3, "primarySkills": ["dribbling", "deception"], "coachingPoints": ["Drop shoulder convincingly — commit to the fake", "Drive must be explosive — not cautious", "Keep ball close to the outside foot", "Look up for the next action immediately"], "difficultyTier": "U14", "skillWeighting": {"deception": 35, "dribbling": 55, "close_control": 10}, "secondarySkills": ["close_control", "agility"], "equipmentRequired": ["ball", "cones"], "recommendedGroupSize": "2–8"}', 'sessDrill.bodyFeintAndDrive', 0, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO session.drills (id, name, description, library_type, owner_coach_id, status, metadata, trans_key, version, source_drill_id) VALUES ('00000000-0000-4000-8000-000000000016', 'Pass and Move (2-Touch)', 'Simple pass and move in pairs — receive, control, pass, move to new position.', 'PLATFORM', NULL, 'ACTIVE', '{"intensity": 2, "repDensity": 30, "matchRealism": 3, "weakFootBias": true, "cognitiveLoad": 2, "pressureLevel": 1, "primarySkills": ["passing", "first_touch"], "coachingPoints": ["Open body before the ball arrives", "Pass into the path of your partner''s run", "Move immediately after the pass", "Weight of pass must match distance"], "difficultyTier": "U8", "skillWeighting": {"passing": 50, "movement": 15, "first_touch": 35}, "secondarySkills": ["movement", "positioning"], "equipmentRequired": ["ball", "cones"], "recommendedGroupSize": "4–12"}', 'sessDrill.passAndMove2Touch', 0, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO session.drills (id, name, description, library_type, owner_coach_id, status, metadata, trans_key, version, source_drill_id) VALUES ('00000000-0000-4000-8000-000000000017', 'Wall Pass (1-2 Combination)', 'Player plays pass to wall player, receives return ball in stride, and continues forward.', 'PLATFORM', NULL, 'ACTIVE', '{"intensity": 3, "repDensity": 20, "matchRealism": 5, "weakFootBias": false, "cognitiveLoad": 3, "pressureLevel": 2, "primarySkills": ["passing", "combination_play"], "coachingPoints": ["Angle body before playing the wall pass", "Drive into space immediately after your pass", "Wall player returns with one touch if possible", "Receiver controls ball into stride — not dead"], "difficultyTier": "U12", "skillWeighting": {"passing": 45, "movement": 15, "combination_play": 40}, "secondarySkills": ["movement", "timing"], "equipmentRequired": ["ball", "cones"], "recommendedGroupSize": "3–8"}', 'sessDrill.wallPassOneTwoCombination', 0, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO session.drills (id, name, description, library_type, owner_coach_id, status, metadata, trans_key, version, source_drill_id) VALUES ('00000000-0000-4000-8000-000000000018', 'Switch of Play from Central', 'Central player receives, spins, and switches play across to opposite wide player under time pressure.', 'PLATFORM', NULL, 'ACTIVE', '{"intensity": 3, "repDensity": 12, "matchRealism": 5, "weakFootBias": false, "cognitiveLoad": 4, "pressureLevel": 3, "primarySkills": ["passing", "switching_play"], "coachingPoints": ["Scan before receiving", "First touch orients toward target", "Long switch must be weighted correctly", "Receiver checks run to meet the ball"], "difficultyTier": "U14", "skillWeighting": {"passing": 50, "awareness": 20, "switching_play": 30}, "secondarySkills": ["first_touch", "awareness", "decision_making"], "equipmentRequired": ["ball", "cones", "bibs"], "recommendedGroupSize": "5–10"}', 'sessDrill.switchOfPlayFromCentral', 0, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO session.drills (id, name, description, library_type, owner_coach_id, status, metadata, trans_key, version, source_drill_id) VALUES ('00000000-0000-4000-8000-000000000019', 'Third-Man Run Combination', 'Two players combine to play in a third runner arriving late into the final third.', 'PLATFORM', NULL, 'ACTIVE', '{"intensity": 4, "repDensity": 8, "matchRealism": 5, "weakFootBias": false, "cognitiveLoad": 5, "pressureLevel": 3, "primarySkills": ["combination_play", "passing"], "coachingPoints": ["Third runner must time the run — not sprint early", "Hold ball long enough to draw the press", "Pass must go in behind the line", "Third man should be onside at the moment of the pass"], "difficultyTier": "U16", "skillWeighting": {"passing": 30, "movement": 20, "combination_play": 50}, "secondarySkills": ["movement", "timing", "awareness"], "equipmentRequired": ["ball", "cones", "bibs", "goal"], "recommendedGroupSize": "6–12"}', 'sessDrill.thirdManRunCombination', 0, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO session.drills (id, name, description, library_type, owner_coach_id, status, metadata, trans_key, version, source_drill_id) VALUES ('00000000-0000-4000-8000-000000000020', 'Receiving in the Half-Turn', 'Player checks to the ball, receives between the lines in a half-turned body position to keep play moving forward.', 'PLATFORM', NULL, 'ACTIVE', '{"intensity": 3, "repDensity": 16, "matchRealism": 5, "weakFootBias": true, "cognitiveLoad": 4, "pressureLevel": 4, "primarySkills": ["first_touch", "receiving_under_pressure"], "coachingPoints": ["Open body sideways before ball arrives", "Check shoulder for pressure before receiving", "First touch goes forward or away from pressure", "Head up instantly to play the next pass"], "difficultyTier": "U16", "skillWeighting": {"awareness": 20, "first_touch": 45, "receiving_under_pressure": 35}, "secondarySkills": ["awareness", "positioning", "passing"], "equipmentRequired": ["ball", "cones", "bibs"], "recommendedGroupSize": "4–8"}', 'sessDrill.receivingInTheHalfTurn', 0, NULL) ON CONFLICT (id) DO NOTHING;

INSERT INTO development.skill_definitions (code, display_name, display_order, active, rubric_criteria) VALUES ('PAC', 'Pace', 1, true, 'Measures maximum sprint speed over 30m and acceleration in the first 10m.') ON CONFLICT (code) DO NOTHING;
INSERT INTO development.skill_definitions (code, display_name, display_order, active, rubric_criteria) VALUES ('SHO', 'Shooting', 2, true, 'Accuracy, power, and composure when shooting on goal from various distances and angles.') ON CONFLICT (code) DO NOTHING;
INSERT INTO development.skill_definitions (code, display_name, display_order, active, rubric_criteria) VALUES ('PAS', 'Passing', 3, true, 'Range, weight, and accuracy of short, medium, and long-range passes under pressure.') ON CONFLICT (code) DO NOTHING;
INSERT INTO development.skill_definitions (code, display_name, display_order, active, rubric_criteria) VALUES ('DRI', 'Dribbling', 4, true, 'Ability to beat an opponent 1v1 using close control, feints, and changes of direction.') ON CONFLICT (code) DO NOTHING;
INSERT INTO development.skill_definitions (code, display_name, display_order, active, rubric_criteria) VALUES ('PHY', 'Physicality', 5, true, 'Strength, balance, and ability to hold off challenges and win physical duels.') ON CONFLICT (code) DO NOTHING;
INSERT INTO development.skill_definitions (code, display_name, display_order, active, rubric_criteria) VALUES ('DEF', 'Defending', 6, true, 'Positioning, timing of tackles, and ability to win the ball cleanly in defensive duels.') ON CONFLICT (code) DO NOTHING;
INSERT INTO development.skill_definitions (code, display_name, display_order, active, rubric_criteria) VALUES ('WEF', 'Weak Foot', 7, true, 'Quality of striking and control using the non-dominant foot in match situations.') ON CONFLICT (code) DO NOTHING;
INSERT INTO development.skill_definitions (code, display_name, display_order, active, rubric_criteria) VALUES ('F1T', 'First Touch', 8, true, 'Control and ability to set up a second touch instantly from various delivery types.') ON CONFLICT (code) DO NOTHING;
INSERT INTO development.skill_definitions (code, display_name, display_order, active, rubric_criteria) VALUES ('FIN', 'Finishing', 9, true, 'Composure and technique in front of goal in 1v1 and tight-angle situations.') ON CONFLICT (code) DO NOTHING;
INSERT INTO development.skill_definitions (code, display_name, display_order, active, rubric_criteria) VALUES ('1V1', 'One vs One', 10, true, 'Ability to beat a goalkeeper or defender in isolated 1v1 attacking situations.') ON CONFLICT (code) DO NOTHING;
INSERT INTO development.skill_definitions (code, display_name, display_order, active, rubric_criteria) VALUES ('HED', 'Heading', 11, true, 'Accuracy and timing of headed attempts at goal or for clearances.') ON CONFLICT (code) DO NOTHING;
INSERT INTO development.skill_definitions (code, display_name, display_order, active, rubric_criteria) VALUES ('CRO', 'Crossing', 12, true, 'Delivery quality and decision-making when crossing from wide positions.') ON CONFLICT (code) DO NOTHING;
INSERT INTO development.skill_definitions (code, display_name, display_order, active, rubric_criteria) VALUES ('IBS', 'In Behind Runs', 13, true, 'Timing and angle of runs in behind a defensive line to receive through-balls.') ON CONFLICT (code) DO NOTHING;
INSERT INTO development.skill_definitions (code, display_name, display_order, active, rubric_criteria) VALUES ('OBS', 'Off-Ball Scanning', 14, true, 'Awareness and head-movement to gather visual information before receiving the ball.') ON CONFLICT (code) DO NOTHING;
INSERT INTO development.skill_definitions (code, display_name, display_order, active, rubric_criteria) VALUES ('FKI', 'Free Kick Inst.', 15, true, 'Technique, accuracy, and power on set-piece deliveries from dead-ball situations.') ON CONFLICT (code) DO NOTHING;

SELECT pg_catalog.setval('main.platform_config_id_seq', 606, true);
